import './sass/main.scss';
import './js/modal-products.js';
import './js/modal-mobile-menu';
import './js/modal-buy-now';
import './js/modal-our-locations';
import './js/modal-franchise2';
import './js/modal-franchise';
import './js/modal-read-more';
import './js/swiper';